#!/usr/bin/env bash
#
# update-grub.sh — Rebuild grub.cfg by scanning ISO partitions
#
# Use this after adding/removing ISOs with add-iso.sh / remove-iso.sh,
# or any time you need to regenerate the GRUB menu.
#
# The script scans all non-ESP, non-Windows GPT partitions on the
# device, mounts each one as ISO9660, detects the distro family,
# and writes a GRUB menu entry that loads the kernel and initrd
# directly from the ISO partition.
#
# GRUB has iso9660 built into the signed binary, so it can read
# these partitions natively — no extraction, no exFAT, no insmod.
#
# Usage:
#   sudo ./update-grub.sh /dev/sdX

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { printf "${GREEN}[INFO]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
die()   { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; exit 1; }

# ── Parse arguments ──────────────────────────────────────────────
DEVICE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            cat <<EOF
Usage: sudo $0 /dev/sdX

Scans ISO partitions on the USB drive and regenerates grub.cfg
on the ESP. Run this after adding or removing ISOs.
EOF
            exit 0
            ;;
        *)
            if [[ -z "$DEVICE" ]]; then
                DEVICE="$1"; shift
            else
                die "Unknown argument: $1"
            fi
            ;;
    esac
done

[[ -n "$DEVICE" ]]       || die "No device specified.  Usage: sudo $0 /dev/sdX"
[[ -b "$DEVICE" ]]       || die "$DEVICE is not a block device"
[[ "$(id -u)" -eq 0 ]]   || die "Must run as root (sudo)"

# ── Detect partition naming style ────────────────────────────────
if [[ "$DEVICE" =~ [0-9]$ ]]; then
    PART_PREFIX="${DEVICE}p"
else
    PART_PREFIX="${DEVICE}"
fi

ESP_DEV="${PART_PREFIX}1"
[[ -b "$ESP_DEV" ]] || die "ESP partition not found: $ESP_DEV"

# ── Mount ESP ────────────────────────────────────────────────────
MNT_ESP=$(mktemp -d)
MNT_PROBE=$(mktemp -d)

cleanup() {
    umount "$MNT_PROBE" 2>/dev/null || true
    umount "$MNT_ESP"   2>/dev/null || true
    rmdir "$MNT_ESP" "$MNT_PROBE" 2>/dev/null || true
}
trap cleanup EXIT

mount "$ESP_DEV" "$MNT_ESP"

[[ -d "$MNT_ESP/EFI/BOOT" ]] || die "ESP does not have EFI/BOOT — run setup.sh first"

ESP_UUID="$(blkid -s UUID -o value "$ESP_DEV" 2>/dev/null || true)"
[[ -n "$ESP_UUID" ]] || die "Could not read UUID for $ESP_DEV"

# ── Distro detection helpers ─────────────────────────────────────
detect_iso_distro() {
    local mnt="$1"
    if [[ -f "$mnt/casper/vmlinuz" ]]; then
        echo "casper"
    elif [[ -f "$mnt/images/pxeboot/vmlinuz" ]]; then
        echo "fedora"
    elif [[ -f "$mnt/live/vmlinuz" ]]; then
        echo "debian-live"
    elif [[ -f "$mnt/arch/boot/x86_64/vmlinuz-linux" ]]; then
        echo "arch"
    elif [[ -f "$mnt/boot/x86_64/loader/linux" ]]; then
        echo "opensuse"
    else
        echo "unknown"
    fi
}

pretty_name() {
    local name="$1"
    name="${name//-/ }"
    name="${name//_/ }"
    echo "$name"
}

# ── Scan all partitions on the device ────────────────────────────
info "Scanning partitions on $DEVICE..."

declare -a ISO_PARTS=()       # device paths for ISO partitions
declare -a WIN_PARTS=()       # device paths for Windows partitions

# Enumerate all partitions (skip the whole-disk entry)
while IFS= read -r part_dev; do
    [[ -b "$part_dev" ]] || continue

    # Skip the ESP (partition 1)
    [[ "$part_dev" == "$ESP_DEV" ]] && continue

    # Identify by filesystem type
    fstype="$(blkid -s TYPE -o value "$part_dev" 2>/dev/null || true)"
    partlabel="$(blkid -s PARTLABEL -o value "$part_dev" 2>/dev/null || true)"

    case "$fstype" in
        iso9660)
            ISO_PARTS+=("$part_dev")
            ;;
        ntfs)
            WIN_PARTS+=("$part_dev")
            ;;
        *)
            if [[ "$fstype" == "udf" ]]; then
                # Some ISOs use UDF — treat as ISO
                ISO_PARTS+=("$part_dev")
            else
                warn "  Skipping $part_dev (fstype=$fstype, label=$partlabel)"
            fi
            ;;
    esac
done < <(lsblk -rno NAME "$DEVICE" 2>/dev/null | tail -n +2 | awk '{print "/dev/" $1}')

info "Found ${#ISO_PARTS[@]} ISO partition(s), ${#WIN_PARTS[@]} Windows partition(s)"

# ── Build grub.cfg ───────────────────────────────────────────────
GRUB_CFG="$MNT_ESP/boot/grub/grub.cfg"
mkdir -p "$(dirname "$GRUB_CFG")"

info "Writing grub.cfg..."

cat > "$GRUB_CFG" <<HEADER
# GRUB2 configuration for multi-boot USB (partition-per-ISO)
#
# Auto-generated by update-grub.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Re-run update-grub.sh after adding/removing ISOs.
#
# Each Linux ISO lives in its own GPT partition (raw dd).
# GRUB reads the kernel and initrd directly from the ISO9660
# filesystem (which is built into the signed grubx64.efi).
# No insmod lines — fully Secure Boot compatible.

set timeout=30
set default=0

HEADER

ENTRY_COUNT=0

if [[ ${#ISO_PARTS[@]} -gt 0 ]]; then
    {
        echo "# ══════════════════════════════════════════════════════════════════"
        echo "#  Linux ISOs (${#ISO_PARTS[@]} found)"
        echo "# ══════════════════════════════════════════════════════════════════"
        echo ""
    } >> "$GRUB_CFG"
fi

for part_dev in "${ISO_PARTS[@]}"; do
    # Get filesystem UUID
    fs_uuid="$(blkid -s UUID -o value "$part_dev" 2>/dev/null || true)"
    if [[ -z "$fs_uuid" ]]; then
        warn "  Could not get UUID for $part_dev — skipping"
        continue
    fi

    # Get GPT partition label (the name we set with sgdisk -c)
    partlabel="$(blkid -s PARTLABEL -o value "$part_dev" 2>/dev/null || true)"
    label="$(pretty_name "${partlabel:-$(basename "$part_dev")}")"

    # Mount and detect distro
    mount -o ro "$part_dev" "$MNT_PROBE" 2>/dev/null || {
        warn "  Could not mount $part_dev — skipping"
        continue
    }

    dtype="$(detect_iso_distro "$MNT_PROBE")"
    umount "$MNT_PROBE" 2>/dev/null || true

    info "  $part_dev → $label ($dtype), UUID=$fs_uuid"

    case "$dtype" in
        casper)
            cat >> "$GRUB_CFG" <<ENTRY
menuentry "$label" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/casper/vmlinuz boot=casper quiet splash ---
    initrd (\$isopart)/casper/initrd
}

menuentry "$label  (safe graphics)" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/casper/vmlinuz boot=casper quiet splash nomodeset ---
    initrd (\$isopart)/casper/initrd
}

ENTRY
            ;;
        fedora)
            cat >> "$GRUB_CFG" <<ENTRY
menuentry "$label" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/images/pxeboot/vmlinuz root=live:UUID=$fs_uuid rd.live.image quiet
    initrd (\$isopart)/images/pxeboot/initrd.img
}

menuentry "$label  (basic graphics)" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/images/pxeboot/vmlinuz root=live:UUID=$fs_uuid rd.live.image nomodeset quiet
    initrd (\$isopart)/images/pxeboot/initrd.img
}

ENTRY
            ;;
        debian-live)
            cat >> "$GRUB_CFG" <<ENTRY
menuentry "$label" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/live/vmlinuz boot=live components quiet splash ---
    initrd (\$isopart)/live/initrd.img
}

menuentry "$label  (safe graphics)" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/live/vmlinuz boot=live components quiet splash nomodeset ---
    initrd (\$isopart)/live/initrd.img
}

ENTRY
            ;;
        arch)
            cat >> "$GRUB_CFG" <<ENTRY
menuentry "$label" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/arch/boot/x86_64/vmlinuz-linux archisodevice=/dev/disk/by-uuid/$fs_uuid
    initrd (\$isopart)/arch/boot/x86_64/initramfs-linux.img
}

menuentry "$label  (safe graphics)" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/arch/boot/x86_64/vmlinuz-linux archisodevice=/dev/disk/by-uuid/$fs_uuid nomodeset
    initrd (\$isopart)/arch/boot/x86_64/initramfs-linux.img
}

ENTRY
            ;;
        opensuse)
            cat >> "$GRUB_CFG" <<ENTRY
menuentry "$label" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/boot/x86_64/loader/linux root=live:UUID=$fs_uuid splash=silent quiet
    initrd (\$isopart)/boot/x86_64/loader/initrd
}

menuentry "$label  (safe graphics)" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/boot/x86_64/loader/linux root=live:UUID=$fs_uuid splash=silent quiet nomodeset
    initrd (\$isopart)/boot/x86_64/loader/initrd
}

ENTRY
            ;;
        *)
            warn "  Unrecognised ISO layout on $part_dev — trying casper fallback"
            cat >> "$GRUB_CFG" <<ENTRY
menuentry "$label  (unrecognised — casper fallback)" {
    search --no-floppy --fs-uuid --set=isopart $fs_uuid
    linux (\$isopart)/casper/vmlinuz boot=casper quiet splash ---
    initrd (\$isopart)/casper/initrd
}

ENTRY
            ;;
    esac

    ((ENTRY_COUNT++)) || true
done

# ── Windows entries ──────────────────────────────────────────────
for part_dev in "${WIN_PARTS[@]}"; do
    win_uuid="$(blkid -s UUID -o value "$part_dev" 2>/dev/null || true)"
    partlabel="$(blkid -s PARTLABEL -o value "$part_dev" 2>/dev/null || true)"

    if [[ -n "$win_uuid" ]]; then
        info "  $part_dev → Windows ($partlabel)"
        cat >> "$GRUB_CFG" <<WINENTRY

# ══════════════════════════════════════════════════════════════════
#  Windows 11
# ══════════════════════════════════════════════════════════════════

menuentry "Windows 11 Installer" {
    search --no-floppy --fs-uuid --set=winpart $win_uuid
    chainloader (\$winpart)/efi/boot/bootx64.efi
}

WINENTRY
    fi
done

# ── No-ISOs placeholder ─────────────────────────────────────────
if [[ $ENTRY_COUNT -eq 0 && ${#WIN_PARTS[@]} -eq 0 ]]; then
    cat >> "$GRUB_CFG" <<'NOISO'
menuentry ">>> No ISOs found — run add-iso.sh to add ISOs <<<" {
    echo "No ISO partitions were found on this drive."
    echo "Run:  sudo ./add-iso.sh /dev/sdX path/to/some.iso"
    sleep 15
}

NOISO
fi

# ── Utility entries ──────────────────────────────────────────────
cat >> "$GRUB_CFG" <<'UTILS'
# ══════════════════════════════════════════════════════════════════
#  Utilities
# ══════════════════════════════════════════════════════════════════

menuentry "UEFI Firmware Settings" {
    fwsetup
}

menuentry "Reboot" {
    reboot
}

menuentry "Power Off" {
    halt
}
UTILS

# ── Update shim redirect ────────────────────────────────────────
if [[ -f "$MNT_ESP/EFI/BOOT/BOOTX64.EFI" ]]; then
    cat > "$MNT_ESP/EFI/BOOT/grub.cfg" <<SHIMCFG
search --no-floppy --fs-uuid --set=esp ${ESP_UUID}
set prefix=(\$esp)/boot/grub
configfile (\$esp)/boot/grub/grub.cfg
SHIMCFG
fi

sync
info "grub.cfg written successfully."
echo ""

# ── Summary ──────────────────────────────────────────────────────
info "$ENTRY_COUNT Linux ISO(s), ${#WIN_PARTS[@]} Windows partition(s)"
info "Menu entries:"
grep -oP '(?<=menuentry ").*(?=")' "$GRUB_CFG" | while IFS= read -r entry; do
    info "  • $entry"
done
echo ""
info "Done. Reboot from the USB to see the updated menu."
